=== PaulGilchrist/dnd-tools/src/data/locations.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Locations Schema",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["index", "name"],
    "properties": {
      "index": {
        "type": "string",
        "description": "Short identifier for the location"
      },
      "name": {
        "type": "string",
        "description": "Full name of the location"
      },
      "book": {
        "type": "string",
        "description": "Source book for the location"
      },
      "desc": {
        "type": "string",
        "description": "Description of the location"
      },
      "image": {
        "type": "string",
        "description": "Image filename for the location"
      },
      "page": {
        "type": "integer",
        "description": "Page number in source book"
      },
      "parent": {
        "type": "string",
        "description": "Parent location if applicable"
      },
      "type": {
        "type": "string",
        "description": "Type of location (city, town, keep, continent, world, area)"
      }
    }
  }
}

=== PaulGilchrist/dnd-tools/src/app/data/locations.json
[{"index":"balders-gate","name":"Balder's Gate","book":"Baldur's Gate - Descent into Avernus","desc":"Baldur's Gate has a reputation for being a rough place, where crime and opportunity walk hand in hand, and where anything can be bought, sold, or seized at sword point. If something can be given a price, it's for sale somewhere in Baldur's Gate. Drugs and poisons sit on shelves alongside tinctures and remedies. Trade goods from Chult, mechanical wonders from Neverwinter, tomes of magic from Calimshan, and the most believable counterfeits of each can all be found in the city's stalls.<br/> <br/> The Flaming Fist, a mercenary company paid for by the city, protects residents without the barest hint of civil delicacy. The Watch, the guardian force of the wealthy Upper City, exists only to serve the patriars- the city's detached upper class. Meanwhile, crime flourishes under the control of the Guild, which oversees almost every organized criminal act, from dockside gambling rings to blackmail at patriar garden parties. Either under the Guild's auspices or in defiance of them, those who cut purses or throats make a decent living in the city, their talents traded as briskly and often just as openly as those of any other professional.<br/> <br/> For all its shadows and dark dealings, Baldur's Gate is not without its lights. Some residents earnestly seek to make the city a safer place by banding together to make their own sort of imperfect but effective justice.","image":"balders-gate-map-player.jpg","page":158,"parent":"faerun","type":"city"},{"index":"faerun","name":"Faerun","book":"Sword Coast Adventurer's Guide","desc":"The vast central continent of Toril, Faerun is a land mass divided by a great sea known as the Inner Sea, or the Sea of Fallen Stars.<br/><br/>To the south lie ancient nations, a tremendous, forbidding jungle, and all manner of lands destroyed or transformed by magical cataclysms and up-heavals. Amid the ruin and the distress in these realms are signs of renewal and hope, as tenacious civilizations and peoples rebuild, reclaim, and create anew.<br/>To the east lie many of the older nations of the Realms, including the Western Heartlands of Faenun- those civilizations centrally located on the continent, and thereby best able to take advantage of trade routes and access to the Sea of Fallen Stars. As in the North, there are cold lands to the east, as well as more temperate regions. As one travels farther east, one moves from lands not so different from one's own to places so foreign they might as well exist on other continents or worlds- which a few of them actually have done.","image":"faerun-map-continent.jpg","page":9,"parent":"toril","type":"continent"},{"index":"toril","name":"Toril","book":"Sword Coast Adventurer's Guide","desc":"Toril is a vast and wondrous world, filled with an immense diversity of peoples and a rich, full history. Toril consists of various continents and islands, including Faer√ªn, Kara-Tur, and Zakhara in the central super-continent and, throughout most of its history Anchorome, Maztica, and Katashaka in the western region of the world. There is also one large and very mysterious continent east of Kara-Tur called Osse whose nature and inhabitants are all but unknown.","image":"toril-map-world.jpg","page":9,"type":"world"},{"index":"waterdeep","name":"Waterdeep","book":"Waterdeep - Dragon Heist","desc":"You'll find no city on the Sword Coast or in all the North half as civilized as Waterdeep. It's not just the law of the land that makes this so, but also the comforts that life here provides.<br/> <br/> In most other towns and cities, you'll start with an early-morning stumble on the stairs as you carry your night soil down to deposit it outside. But in Waterdeep. many buildings are connected directly to the sewers. Public facilities for those out and about can be found all around the Market and the Field of Triumph, and near the largest city squares. ln places without ready access to sewers or public outhouses. members of the Dungsweepers' Guild make multiple rounds each day, collecting urine and excrement separately-for use in industry and agriculture, respectively. Take comfort that in Waterdeep,you'll always find a pot to piss in.<br/> <br/> Also notice how clean the streets are kept. This upkeep is due in large part to the hard work of the Dungsweepers' Guild. Dungsweepers can be seen working their brooms and carts at every hour of the day -and for a few hours after dark- all over the city, removing not just animal dung but other refuse. This service is free to all, paid for by taxes rendered to the city-although an egregious amount of trash left for pickup does result in a separate bill from the guild.<br/> <br/> Another amenity soon appreciated by visitors is Waterdeep's water system. With public fountains and wells all about the city, clean water is plentiful. Many buildings have pumps of their own to draw water from the local supply, and some even possess taps that pour out water with the twist of a knob. This convenience is made possible by the inventiveness of the Gondar, the industry of the Cellarers' and Plumbers' Guild. and the magic that Waterdeep inherited from the Illefarni elves.<br/> <br/> Waterdeep is also a city of light. Continual flame spells illuminate many signs and streetlamps in the wealthier parts of the city. Elsewhere, the Guild of Chandlers and Lamplighters keeps the streets lit (excepting the Field Ward and the most dangerous areas of the Dock Ward). Not only that, but hundreds of driftglobes bob about the City of the Dead at night, departing to float over the rest of the city each morning. Such is not typical behavior for driftglobes, I assure you!<br/> <br/> Lastly, no city in the world is as literate as Waterdeep. Oghma's priests from the Font of Knowledge offer free instruction in reading to all who desire it, and the city has over thirty publishers of broadsheets in addition to chapbook printers and book publishers. Large paper advertisements are plastered onto alley walls, and smaller ones are passed out by those hired by businesses to trumpet their services. Printed menus can be found posted in the windows of most eateries and are handed out to those who dine within. Admittedly, you'll see less reading material in the Dock Ward and the Field Ward, but this fact is notable only because of its preponderance elsewhere.","image":"waterdeep-map-player.jpg","page":181,"parent":"faerun","type":"city"}]
